### ISSUE TITLE
[Bug]: ZE_RESULT_ERROR_DEVICE_LOST when running inference on the NPU

### ISSUE THREAD

**Issue by maciej-procero** [openvinotoolkit/openvino#29386]
### OpenVINO Version

2025.0.1

### Operating System

Windows System

### Device used for inference

NPU

### Framework

ONNX

### Model used

DDColor

### Issue description

I am experimenting with running different models on the NPU/GPU. I am currently using an image colorization model, and I am able to compile it for the CPU/GPU/NPU. It runs fine on GPU and CPU and only sometimes on NPU. About 50% of the time, the model crashes with `ZE_RESULT_ERROR_DEVICE_LOST, code 0x70000001`

The model: 
https://github.com/piddnad/DDColor

### Step-by-step reproduction

1. Convert the model to onnx file using 
     ```
     torch.onnx.export(model=model, args=inputs, f=filename)
     ```
2. Use `read_model` to get the model 
3. Compile model for the NPU
4. Load compiled model 
5. Iterate through images and process each image one by one 

Each time step 5 executes, the model does process at least one image before crashing 

The code: 
```
import os

import _paths  # noqa: F401
import cv2
import numpy as np
import torch
import torch.nn.functional as F
from ddcolor_model import DDColor
from huggingface_hub import PyTorchModelHubMixin
from infer import ImageColorizationPipeline
from tqdm import tqdm

import libs.intel_compile as intel

device = 'NPU'

size = 512
onnx_file = f'ddc_{size}_{device}.onnx'
model_file = f'ddc_{size}_{device}.intl'


class DDColorHF(DDColor, PyTorchModelHubMixin):
    def __init__(self, config):
        super().__init__(**config)


class ImageColorizationPipelineHF(ImageColorizationPipeline):
    def __init__(self, model, input_size):
        self.input_size = input_size
        self.model = model

    @torch.no_grad()
    def process(self, img):
        height, width = img.shape[:2]

        img = (img / 255.0).astype(np.float32)
        orig_l = cv2.cvtColor(img, cv2.COLOR_BGR2Lab)[:, :, :1]  # (h, w, 1)

        # Resize and convert image to grayscale
        img_resized = cv2.resize(img, (self.input_size, self.input_size))
        img_l = cv2.cvtColor(img_resized, cv2.COLOR_BGR2Lab)[:, :, :1]
        img_gray_lab = np.concatenate((img_l, np.zeros_like(img_l), np.zeros_like(img_l)), axis=-1)
        img_gray_rgb = cv2.cvtColor(img_gray_lab, cv2.COLOR_LAB2RGB)

        tensor_gray_rgb = torch.from_numpy(img_gray_rgb.transpose((2, 0, 1))).float().unsqueeze(0)

        output_abc = self.model(tensor_gray_rgb)  # .cpu()  # (1, 2, self.input_size, self.input_size)
        output_ab = torch.tensor(output_abc[0])
        # Resize output and concatenate with original L channel
        output_ab_resized = F.interpolate(output_ab, size=(height, width))[0].float().numpy().transpose(1, 2, 0)
        output_lab = np.concatenate((orig_l, output_ab_resized), axis=-1)
        output_bgr = cv2.cvtColor(output_lab, cv2.COLOR_LAB2BGR)

        output_img = (output_bgr * 255.0).round().astype(np.uint8)
        return output_img


if not os.path.exists(path=onnx_file):
    print('creating onnx file')
    ddcolor_model: DDColorHF = DDColorHF.from_pretrained(pretrained_model_name_or_path='piddnad/ddcolor_modelscope')
    model = intel.convert_to_onnx(model=ddcolor_model, inputs=torch.rand((1, 3, size, size)), filename=onnx_file)
if not os.path.exists(model_file):
    print('creating intl file')
    model = intel.model_from_onnx(onnx_path=onnx_file)
    model_compiled = intel.compile_model(model=model, device=device)
    intel.save_compiled_model(compiled_model=model_compiled, name=model_file)

model_compiled = intel.load_compiled_model(path=model_file, device=device)

input_dir = 'img'
output_dir = f'results_{size}_{device}'

img_list: list[str] = os.listdir(input_dir)

colorizer = ImageColorizationPipelineHF(model=model_compiled, input_size=size)

if not os.path.exists(output_dir):
    os.makedirs(output_dir)

for name in tqdm(img_list):
    img = cv2.imread(os.path.join(input_dir, name))
    image_out = colorizer.process(img)
    cv2.imwrite(os.path.join(output_dir, name), image_out)

```

```
def convert_to_onnx(model, inputs, filename) -> None:
    if os.path.exists(filename):
        print(f'File {filename} already exists. Skipping conversion.')
        return
    torch.onnx.export(model=model, args=inputs, f=filename)
    return


def load_compiled_model(path, device) -> ov.CompiledModel:
    with open(path, 'rb') as f:
        user_stream = f.read()
    return core.import_model(user_stream, device_name=device)


def save_compiled_model(compiled_model, name) -> None:
    if os.path.exists(name):
        print(f'File {name} already exists. Skipping saving.')
        return
    user_stream = compiled_model.export_model()
    with open(f'./{name}', 'wb') as f:
        f.write(user_stream)
    return


def model_from_onnx(onnx_path) -> ov.Model:
    return core.read_model(model=onnx_path)


def model_from_pytorch(model, inputs) -> ov.Model:
    return ov.convert_model(input_model=model, example_input=inputs)


def compile_model(model: ov.Model, device: str) -> ov.CompiledModel:
    return ov.compile_model(model=model, device_name=device)

```

### Relevant log output

```shell
File "C:\ProgramData\miniconda3\envs\exp_intel\lib\site-packages\torch\utils\_contextlib.py", line 116, in decorate_context
    return func(*args, **kwargs)
  File "c:\Users\Maciej\programming\experiments\colorization_models\DDColor-master\intel_compiled_ddc.py", line 47, in process
    output_abc = self.model(tensor_gray_rgb)  # .cpu()  # (1, 2, self.input_size, self.input_size)
  File "C:\ProgramData\miniconda3\envs\exp_intel\lib\site-packages\openvino\runtime\ie_api.py", line 388, in __call__
    return self._infer_request.infer(
23:
Exception from src\plugins\intel_npu\src\utils\src\zero\zero_wrappers.cpp:154:
L0 zeCommandQueueExecuteCommandLists result: ZE_RESULT_ERROR_DEVICE_LOST, code 0x70000001 - device hung, reset, was removed, or driver update occurred
```

### Issue submission checklist

- [x] I'm reporting an issue. It's not a question.
- [x] I checked the problem with the documentation, FAQ, open issues, Stack Overflow, etc., and have not found a solution.
- [x] There is reproducer code and related data files such as images, videos, models, etc.

**Comment by maciej-procero** [comment]
Hi,
I will retest with the new driver today. For the model I first converted it into onnx and then compile it (You can see a convenience function in the code I posted) I could share the file with you, what method would work best?

**Comment by avitial** [comment]
@maciej-procero thanks! You can share them here if model files are not too big, otherwise you can share via google drive or any other method of your preference.

**Comment by maciej-procero** [comment]
I have an update. It seems that the issue I am experiencing is with the dev kit I am using. When I tried running my code on a intel provided machine it worked without an issue

**Comment by avitial** [comment]
Thanks for the update, I am glad the issue has been resolved. Closing this issue has been addressed. Feel free to reopen and ask any questions related to this topic if the issue persists.
