### ISSUE TITLE
[Bug]:  Pad operation with float64 initializer produces incorrect results on GPU devices

### ISSUE THREAD

**Issue by zhihaoxu1325** [openvinotoolkit/openvino#33463]
### OpenVINO Version

2025.4.0

### Operating System

Ubuntu 20.04 (LTS)

### Device used for inference

GPU

### Framework

None

### Issue description

The GPU plugin produces incorrect (zero/garbage) values when executing `Pad` operation with float64 (double) initializer input. All padding modes are affected. The bug does not occur with float32 or when the input is a runtime tensor.

**Affected Configuration**
- Parameter: input data type
- Affected Values: float64 (double)
- Working Values: float32

- Parameter: input source  
- Affected Values: initializer (constant)
- Working Values: runtime input

**Root Cause Hypothesis**

The GPU constant folding or kernel for Pad operation appears to have incorrect memory handling for float64 constants. The output values (zeros or garbage like `2.31393671e+00`, `-1.08420217e-19`) suggest reading from uninitialized memory.

### Step-by-step reproduction

Please run the minimal Reproduction Scripts:

```
import numpy as np
import onnx
from onnx import helper, TensorProto, numpy_helper
import openvino as ov

# Create minimal ONNX model: Pad with float64 initializer
v30_data = np.array([[[4.92198038], [5.02298737], [4.59415817]]], dtype=np.float64)
pads_data = np.array([0, -1, 0, 0, -1, 0], dtype=np.int64)

v30_init = numpy_helper.from_array(v30_data, 'v30')
pads_init = numpy_helper.from_array(pads_data, 'pads')
output = helper.make_tensor_value_info('output', TensorProto.DOUBLE, None)

pad_node = helper.make_node('Pad', ['v30', 'pads'], ['output'], mode='reflect')
graph = helper.make_graph([pad_node], 'test', [], [output], [v30_init, pads_init])
model = helper.make_model(graph, opset_imports=[helper.make_opsetid('', 14)])
onnx.save(model, 'pad_float64_bug.onnx')

# Test
core = ov.Core()
compiled_cpu = core.compile_model('pad_float64_bug.onnx', 'CPU')
compiled_gpu = core.compile_model('pad_float64_bug.onnx', 'GPU')

result_cpu = compiled_cpu({})[0]
result_gpu = compiled_gpu({})[0]

print(f"Expected (CPU): {result_cpu.flatten()}")
print(f"Actual (GPU):   {result_gpu.flatten()}")
print(f"Match: {np.allclose(result_cpu, result_gpu)}")
```

### Relevant log output

```shell
Expected (CPU): [5.02298737]
Actual (GPU):   [0.]
Match: False
```

### Issue submission checklist

- [x] I'm reporting an issue. It's not a question.
- [ ] I checked the problem with the documentation, FAQ, open issues, Stack Overflow, etc., and have not found a solution.
- [x] There is reproducer code and related data files such as images, videos, models, etc.

**Comment by hannah-mnq** [comment]
I’d like to work on this issue.
I can reproduce it and will start investigating the GPU Pad implementation.

**Comment by gupta-nu** [comment]
.take

**Comment by Wan-Intel** [comment]
Hello @zhihaoxu1325 

I've validated your application with OpenVINO nightly. The issue has been fixed. You may install OpenVINO nightly via the following command:
`pip install --pre openvino openvino-tokenizers openvino-genai --extra-index-url https://storage.openvinotoolkit.org/simple/wheels/nightly`

<img width="801" height="91" alt="Image" src="https://github.com/user-attachments/assets/84b7c48e-49d9-4d96-9f78-ded5e519b1ca" />

**Comment by Wan-Intel** [comment]
Closing, feel free to re-open or start a new issue if additional assistance is needed.
