### ISSUE TITLE
Wrong result on FP16 GPU device

### ISSUE THREAD

**Issue by saiyajin-sp** [openvinotoolkit/openvino#438]
Using opevnino version 2020.1.033 (windows10 with UHD Grahics 620) to perform image classification problem.

Inference code referred to classification_sample_async.
Using the ONNX model created based on VGG16, IR models of FP32 and FP16 were created.

In FP32, inference is completed normally for both CPU and GPU devices, and the results are both correct.
```
classid probability
------- -----------
0       0.9631082
1       0.0368918
4       0.0000000
3       0.0000000
2       0.0000000
```
However, on FP16 GPU devices, the inference is complete but the results are incorrect.
```
classid probability
------- -----------
4       0.3332520
2       0.3332520
0       0.3332520
3       0.0000055
1       0.0000055
```

In C ++ and Python implementation code, both have similar results.

Since the FP32 is operating normally, I think there is no problem with the original model itself.
Is there any problem with converting to FP16 with mo.py or the inference engine core?

Please advise if you have any solution tips.

Thanks.

**Comment by brmarkus** [comment]
Can you provide more details about the ONNX model, please, you said "based on VGG16", is it publicly available to that it could be used for analysis?

Can you provide the full command lines of how you have converted the models to IR format, please?

Did you use the original sample "classification_sample_async" or applied changes?
Can you provide the full command lines of how you called it?

**Comment by saiyajin-sp** [comment]
Hi@brmarkus

My model is customized based on the general network of VGG16.
Only the layers after the linear layer are tuned to fit the dataset.
Although the file size is quite large, I will consider attachment if necessary.

I tried the following two types of commands when creating IR models on FP16.

```
python "C:\Program Files (x86)\IntelSWTools\openvino_2020.1.033\deployment_tools\model_optimizer\mo.py"
 --input_model (my ONNX model path and name)  --data_type FP16  --output_dir .\output --mean_values (103.939,116.779,123.68)
```
```
python "C:\Program Files (x86)\IntelSWTools\openvino_2020.1.033\deployment_tools\model_optimizer\mo_onnx.py"
 --input_model (my ONNX model path and name)  --data_type FP16  --output_dir .\output --mean_values (103.939,116.779,123.68)
```
The mean_values are generic values for VGG16.


I used the original sample "classification_sample_async". 
The command line in Python is:
```
python .\classification_async.py -m  (my IR(xml) model path and name) -i (my image file path and name) -d GPU
```

Thanks.

**Comment by saiyajin-sp** [comment]
I noticed a new fact.

The result is NG with one image, but the accuracy is obtained with multiple images.

Thanks.

**Comment by Laubeee** [comment]
I think this is a general problem. I have a similar issue when running the hpe0001 model from the model zoo.

I wanted one that's optimized for speed, so I tried the FP16-INT8:
`human_pose_estimation_demo.exe -m "[...]\models\intel\human-pose-estimation-0001\FP16-INT8\human-pose-estimation-0001.xml"`
gives fine results, ~4/12fps (sync/async)

but with GPU:
`human_pose_estimation_demo.exe -m "[...]\models\intel\human-pose-estimation-0001\FP16-INT8\human-pose-estimation-0001.xml" -d GPU`
I get complete bullshit-results and fps of ~4/6 (sync/async) which is quite bad, especially async. The detected keypoints are mainly at the upper border and some random points like shoulder-to-belly.

when changing to FP32:
`human_pose_estimation_demo.exe -m "[...]\models\intel\human-pose-estimation-0001\FP32\human-pose-estimation-0001.xml" -d GPU`
I get fine results and ~8/13fps

Interestingly, when loading this model in OpenCV (both FP16-INT8 and FP32), the detection is also quite bad, although I don't think the GPU is used.. (I currently don't know how to "turn on GPU" when using `cv.dnn.readNet()`, is there a way? a guide/tutorial on this would be nice. Also the "model docs" dont state anything about what the input is to be expected in terms of scaling or RGB/BGR filp)

P.S. are the long wait times with `-d GPU` normal? it takes like half a minute to start the demo...

**Comment by Laubeee** [comment]
@vladimir-paramuzov ping
Is there anyone working on this? It seems to affect a broader amount of cases (may be related to 620s series of GPU)

**Comment by vladimir-paramuzov** [comment]
@saiyajin-sp I checked all vgg-like models that we have and didn't find any issues with FP16 precision. Could you please try latest openvino versions and check if the issue still exists? If yes, then it'd be great to have your model for the analysis. Also, please make sure that the values in weights are suitable for FP16 data type and doesn't lead to overflow/huge representation errors.

@Laubeee 

> I wanted one that's optimized for speed, so I tried the FP16-INT8:

Such model precision is not really good choice for your GPU, because this model is quantized for int8 exectuion, but your GPU doesn't have hardware acceleration for int8 models.

As for the accuracy, do you observe any issues with FP16 model? Also, please try newer openvino version (2020/4 release or master branch), as I don't see any issues for this model in the latest validation reports. 

> P.S. are the long wait times with -d GPU normal? it takes like half a minute to start the demo...

Most of the time is spent on OCL kernels compilation. Consider enabling [cl_cache](https://github.com/intel/compute-runtime/blob/master/opencl/doc/FAQ.md#feature-cl_cache)

**Comment by Laubeee** [comment]
I see. Thanks for the explanation. Pure FP16 works fine in 2020/3
Any suggestions on using GPU with OpenCV?

**Comment by vladimir-paramuzov** [comment]
@dkurt @alalek Could you answer the question (below) regarding OpenCV?

> Interestingly, when loading this model in OpenCV (both FP16-INT8 and FP32), the detection is also quite bad, although I don't think the GPU is used.. (I currently don't know how to "turn on GPU" when using cv.dnn.readNet(), is there a way? a guide/tutorial on this would be nice. Also the "model docs" dont state anything about what the input is to be expected in terms of scaling or RGB/BGR filp)

**Comment by dkurt** [comment]
@vladimir-paramuzov, I cano only recommend to read the [tutorials](https://docs.opencv.org/master/d2/d58/tutorial_table_of_content_dnn.html) and try to run [samples](https://github.com/opencv/opencv/tree/master/samples/dnn).

**Comment by Laubeee** [comment]
Hi @dkurt thanks - I have (also previously) looked at some of them, and so far I don't see anything they do explicitly to use GPU. Also I don't see any samples or tutorials that specifically mention GPU... am I missing something?
I do get a speedup from using the OpenVINO-build when following the examples and tutorials (so it obviously uses the IE), but GPU usage remains at near 0.

What I did find, though, was this [guide on HETERO plugin](https://docs.openvinotoolkit.org/2020.3/_docs_IE_DG_supported_plugins_HETERO.html) which seems to do what I want, just not with OpenCV but rather using the IE-API directly. I'll try to translate it to Python later and report whether I got it to work.
However if this is the only way to do this currently I think it might be worth discussion whether this functionality should be made available through OpenCV as well. If there is already a way, as stated, a dedicated guide / tutorial seems to be missing.

(Sorry this ended up here, in an issue that has nothing to do with this. Feel free to re-organize into a new issue as you seem fit, if necessary.)

**Comment by dkurt** [comment]
@Laubeee, please take a look at https://github.com/opencv/opencv/wiki/Intel%27s-Deep-Learning-Inference-Engine-backend as well. It's too simple to dedicate a separate guide to switch the computational targets:

```cpp
net.setPreferableTarget(DNN_TARGET_OPENCL);
```

**Comment by Laubeee** [comment]
Huh, wow, ok. Of course I missed this..
Then I can google all I want about "how to set target device in opencv openvino", the oneliner will never pop up^^
thx anyway
